#!/bin/bash

path=/usr/bin/htop

# if command -v $path
if [ -f $path ]
then
    echo "The file exit. Let run it...."
    htop

else
    echo " The file does not exits. Let installing it ...."
    sudo apt update && sudo apt install -y htop

fi


